export const INDONESIA_CITIES = [
  'Surabaya',
  'Kota Malang',
  'Malang',
  'Kediri',
  'Blitar',
  'Madiun',
  'Mojokerto',
  'Pasuruan',
  'Probolinggo',
  'Banyuwangi',
  'Jember',
  'Bondowoso',
  'Situbondo',
  'Lumajang',
  'Sidoarjo',
  'Gresik',
  'Lamongan',
  'Tuban',
  'Bojonegoro',
  'Ngawi',
  'Magetan',
  'Ponorogo',
  'Pacitan',
  'Trenggalek',
  'Tulungagung',
  'Nganjuk',
  'Jombang',
  'Sampang',
  'Pamekasan',
  'Sumenep',
  'Bangkalan',

  // Jawa Tengah & DIY
  'Semarang',
  'Solo',
  'Surakarta',
  'Sleman',
  'Kota Yogyakarta',
  'Magelang',
  'Salatiga',
  'Pekalongan',
  'Tegal',
  'Sukoharjo',
  'Karanganyar',
  'Sragen',
  'Grobogan',
  'Blora',
  'Rembang',
  'Pati',
  'Kudus',
  'Jepara',
  'Demak',
  'Temanggung',
  'Kendal',
  'Batang',
  'Pemalang',
  'Brebes',
  'Cilacap',
  'Banyumas',
  'Purbalingga',
  'Banjarnegara',
  'Kebumen',
  'Purworejo',
  'Wonosobo',
  'Boyolali',
  'Klaten',
  'Wonogiri',
  'Kulonprogo',
  'Bantul',
  'Gunungkidul',

  // Jawa Barat & Jakarta
  'Jakarta',
  'Bandung',
  'Bogor',
  'Depok',
  'Bekasi',
  'Tangerang',
  'Cirebon',
  'Sukabumi',
  'Tasikmalaya',
  'Garut',
  'Cianjur',
  'Kuningan',
  'Majalengka',
  'Sumedang',
  'Indramayu',
  'Subang',
  'Purwakarta',
  'Karawang',
  'Ciamis',
  'Banjar',
  'Pangandaran',

  // Kota-kota besar lainnya
  'Medan',
  'Palembang',
  'Makassar',
  'Denpasar',
  'Banjarmasin',
  'Balikpapan',
  'Samarinda',
  'Pontianak',
  'Pekanbaru',
  'Jambi',
  'Bengkulu',
  'Lampung',
  'Serang',
  'Cilegon',
  'Tangerang Selatan',
  'Depok',
  'Bekasi',
  'Batam',
  'Palu',
  'Manado',
  'Ambon',
  'Kupang',
  'Jayapura',
  'Sorong',
  'Mataram',
  'Bima',

  // Kabupaten
  'Sidoarjo',
  'Gresik',
  'Lamongan',
  'Mojokerto',
  'Jombang',
  'Bojonegoro',
  'Tuban',
  'Banyuwangi',
  'Jember',
  'Lumajang',
  'Probolinggo',
  'Pasuruan',
  'Malang',
  'Blitar',
  'Kediri',
  'Nganjuk',
  'Madiun',
  'Magetan',
  'Ngawi',
  'Pacitan',
  'Ponorogo',
  'Trenggalek',
  'Tulungagung',
  'Bondowoso',
  'Situbondo',
  'Sumenep',
  'Pamekasan',
  'Sampang',
  'Bangkalan',
  'Sukoharjo',
  'Karanganyar',
  'Sragen',
  'Grobogan',
  'Blora',
  'Rembang',
  'Pati',
  'Kudus',
  'Jepara',
  'Demak',
  'Semarang',
  'Temanggung',
  'Kendal',
  'Batang',
  'Pekalongan',
  'Pemalang',
  'Tegal',
  'Brebes',
  'Cilacap',
  'Banyumas',
  'Purbalingga',
  'Banjarnegara',
  'Kebumen',
  'Purworejo',
  'Wonosobo',
  'Magelang',
  'Boyolali',
  'Klaten',
  'Wonogiri',
  'Karanganyar',
  'Sukoharjo',
  'Kulonprogo',
  'Bantul',
  'Gunungkidul',
  'Sleman',
];

export const INDONESIA_PROVINCES = [
  'Jawa Timur',
  'Jawa Tengah',
  'Jawa Barat',
  'DKI Jakarta',
  'Jakarta',
  'Sumatera Utara',
  'Sumatera Barat',
  'Sumatera Selatan',
  'Riau',
  'Kalimantan Timur',
  'Kalimantan Barat',
  'Kalimantan Selatan',
  'Kalimantan Tengah',
  'Kalimantan Utara',
  'Sulawesi Selatan',
  'Sulawesi Utara',
  'Sulawesi Tengah',
  'Sulawesi Tenggara',
  'Sulawesi Barat',
  'Gorontalo',
  'Bali',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'NTB',
  'NTT',
  'Maluku',
  'Maluku Utara',
  'Papua',
  'Papua Barat',
  'Papua Selatan',
  'Papua Tengah',
  'Papua Pegunungan',
  'Lampung',
  'Bengkulu',
  'Jambi',
  'Kepulauan Riau',
  'Kepulauan Bangka Belitung',
  'Daerah Istimewa Yogyakarta',
  'Yogyakarta',
  'Aceh',
];

export const LOCATION_PATTERNS = [
  // Universitas & Institusi Pendidikan
  /\b(universitas|institut|akademi|sekolah|kampus|its|ui|ugm|itb|unair|unesa|uny|undip|uns|unpad|unhas|unsrat|unud)\b/i,
  /\b(teknologi|sepuluh|nopember|indonesia|gadjah|mada|brawijaya|airlangga|negeri|swasta|politeknik|stikes)\b/i,

  // Tempat Ibadah & Landmark
  /\b(masjid|gereja|kuil|pura|vihara|candi|monumen|tugu|alun-alun)\b/i,

  // Fasilitas Umum
  /\b(rumah\s*sakit|puskesmas|balai\s*kota|kantor|stasiun|terminal|bandara|pelabuhan|mall|plaza|hotel)\b/i,

  // Jalan & Area
  /\b(jalan|jl\.|gang|gg\.|perumahan|komplek|ruko|gedung|tower|apartemen)\b/i,

  // Nomor & Kode
  /\b(no\.|nomor|rt|rw|blok|kav)\b/i,
];
